[package]
name = "wget"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.26"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.11", features = ["stream"] }
url = "2.2"